# -*- coding: utf-8 -*-
#
# Aristotle Metadata Registry User Documentation documentation build configuration file, created by
# sphinx-quickstart on Sat Mar 11 00:33:15 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath('../python'))

# screenshots_server_path = "http://%s"% os.getenv('DOCS_SERVER_URL', 'http://0.0.0.0:8080')
# screenshots_read_path = '/_static/screenshots'
# screenshots_save_path = os.path.abspath(os.path.join('.',screenshots_read_path[1:]))
# screenshots_logout_path = "/logout"
# screenshots_driver = os.getenv("SELENIUM_DRIVER", "selenium.webdriver.Chrome")

# # Clean up past screenshots
# filelist = [ f for f in os.listdir(screenshots_save_path) if f.endswith(".png") ]
# for f in filelist:
#     os.remove(os.path.join(screenshots_save_path,f))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    # 'sphinxcontrib.rawfiles',
    'sphinx.ext.todo',
    'sphinx.ext.githubpages',
    # 'selenium_screenshots.screener',
    'sphinxcontrib.fulltoc',
    'clean_index.builder'
]

# rawfiles = ['CNAME']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Aristotle Metadata Registry User Documentation'
copyright = u'2019, Aristotle Metadata Registry'
author = u'Aristotle Metadata Registry'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'3.0.2'
# The full version, including alpha/beta/rc tags.
release = u'3.0.2'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

html_show_sourcelink = False

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme_path = ["_themes", ]
# import solar_theme

# html_theme = 'aristotle_theme'
import aristotle_theme

html_theme = 'aristotle_theme'
html_theme_path = [aristotle_theme.theme_path]

# html_theme_path = [aristotle_theme.theme_path]
# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static',]
html_short_title = "Aristotle Help"

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'AristotleMetadataRegistryUserDocumentationdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'AristotleMetadataRegistryUserDocumentation.tex', u'Aristotle Metadata Registry User Documentation Documentation',
     u'Aristotle Metadata Registry', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'aristotlemetadataregistryuserdocumentation', u'Aristotle Metadata Registry User Documentation Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'AristotleMetadataRegistryUserDocumentation', u'Aristotle Metadata Registry User Documentation Documentation',
     author, 'AristotleMetadataRegistryUserDocumentation', 'One line description of project.',
     'Miscellaneous'),
]



